FROM python:3.8-slim-buster

ADD script.py /

RUN apt-get update -y \
    && apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev libsnmp-dev -y

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD [ "python", "./script.py" ]